In [1]:
# K-Nearest Neighbors (K-NN)

# Importing the libraries
import numpy as np
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('emails.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
'''
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)
'''
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)


# Training the K-NN model on the Training set
print("\n***************KNN********************* ")
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

# Predicting a new result
#print("Predicted Salary for [45,22000]::",classifier.predict(sc.transform([[45,22000]])))

# Predicting the Test set results
y_pred_KNN = classifier.predict(X_test)
print(np.concatenate((y_pred_KNN.reshape(len(y_pred_KNN),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_KNN)
print(cm)
print ('Accuracy of KNN ::',accuracy_score(y_test, y_pred_KNN))

######SVM
# Training the SVM model on the Training set
print("\n***************SVM********************* ")

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred_SVC = classifier.predict(X_test)
print(np.concatenate((y_pred_SVC.reshape(len(y_pred_SVC),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_SVC)
print(cm)
print ('Accuracy of KNN ::',accuracy_score(y_test, y_pred_SVC))


[[32 25 14 ...  0  1  0]
 [42 19  1 ...  0  3  0]
 [ 1  3  1 ...  0  0  0]
 ...
 [12 18  8 ...  0  2  0]
 [10  6 96 ...  0  1  0]
 [ 1  8  2 ...  0  0  0]]
[0 1 1 ... 1 0 1]
[[14  7  2 ...  0  0  0]
 [ 6  2  1 ...  0  0  0]
 [40  6  4 ...  0  1  0]
 ...
 [ 3  1  1 ...  0  0  0]
 [ 8  3 12 ...  0  0  0]
 [ 1  6  2 ...  0  2  0]]
[0 0 0 ... 0 0 1]
[[ 2.17234981  1.9271617   0.60399561 ... -0.05798835  0.02459753
  -0.07126366]
 [ 3.02915007  1.30898893 -0.28953232 ... -0.05798835  0.77294125
  -0.07126366]
 [-0.48373101 -0.33947178 -0.28953232 ... -0.05798835 -0.34957433
  -0.07126366]
 ...
 [ 0.45874928  1.20596014  0.1915981  ... -0.05798835  0.39876939
  -0.07126366]
 [ 0.28738923 -0.03038539  6.2400949  ... -0.05798835  0.02459753
  -0.07126366]
 [-0.48373101  0.1756722  -0.22079941 ... -0.05798835 -0.34957433
  -0.07126366]]
[[ 0.63010934  0.0726434  -0.22079941 ... -0.05798835 -0.34957433
  -0.07126366]
 [-0.05533088 -0.44250057 -0.28953232 ... -0.05798835 -0.34957433
  -0.07126366

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


[[1 0]
 [0 0]
 [0 0]
 ...
 [1 0]
 [0 0]
 [1 1]]
[[735 194]
 [ 23 341]]
Accuracy of KNN :: 0.8321732405259087

***************SVM********************* 
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]
[[890  39]
 [ 26 338]]
Accuracy of KNN :: 0.9497293116782676
